# Generated by Django 5.0.1 on 2024-01-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.SmallIntegerField(null=True),
        ),
    ]
